name: everydaybible
description: Everyday Read Bible Amen.

version: 2.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter:
  cupertino_icons: ^1.0.2
  http:
  intl:

  # UI
  fluent_ui: ^4.0.2
  flutter_slidable:
  table_calendar:

  # Database
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # StateManage
  flutter_bloc:
  bloc:

  # Network
  dio: any

  # Utils
  equatable:
  dartz:
  html:
  collection:

  just_audio: ^0.9.29
  just_audio_mpv: any

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  macos:
    generate: true
flutter:
  uses-material-design: true
  fonts:
    - family: Fondamento
      fonts:
        - asset: assets/fonts/Fondamento-Regular.ttf
    - family: Norican
      fonts:
        - asset: assets/fonts/Norican-Regular.ttf

  assets:
    - assets/
    - assets/data/bible.json
