name: everydaybible
description: Everyday Read Bible Amen.

version: 2.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.17.0
  just_audio: ^0.7.3
  font_awesome_flutter:

  flutter_zoom_drawer:
  scroll_to_index: any

  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http:
  intl:
  get: ^4.1.3
  hive: ^2.0.0
  hive_flutter: ^1.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/everyday_bible_launcher_icon.png"
flutter:
  uses-material-design: true
  fonts:
  - family: Fondamento
    fonts:
    - asset: assets/fonts/Fondamento-Regular.ttf
  - family: Norican
    fonts:
    - asset: assets/fonts/Norican-Regular.ttf

  assets:
    - assets/bible_db/kor_gg_bible/
